# Generated by Django 2.1.5 on 2019-04-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='usuario_img'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='dorsal',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
