# Generated by Django 2.1.5 on 2019-04-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20190410_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
