# Generated by Django 2.1.5 on 2019-02-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJ', models.CharField(blank=True, max_length=250, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('posicion', models.CharField(blank=True, max_length=100, null=True)),
                ('nacimiento', models.DateField(blank=True)),
                ('dorsal', models.CharField(blank=True, max_length=3, null=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='img-jugador')),
                ('estatus', models.CharField(choices=[('A', 'ACTIVO'), ('L', 'LESIONADO'), ('S', 'SUSPENDIDO')], max_length=1)),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.equipo')),
            ],
        ),
    ]
