# Generated by Django 2.1.5 on 2019-03-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_jugador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='Equipo',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='nombreJ',
            new_name='nombre',
        ),
    ]
